name: Exadel-Task-Four

on:
    push:
        branches:
                - master

env:
    USER: "jamshidyerzakov"
    PROJECT: "task4"

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Docker login
          run: docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
        - name: Build the Docker image
          run: docker build -t $USER/$PROJECT:latest ./task_4/.
        - name: Push Docker image to dockerhub
          run: docker push $USER/$PROJECT:latest
